# Generated by Django 2.0.5 on 2018-05-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100, verbose_name='book_id')),
                ('book_type', models.CharField(blank=True, max_length=255, verbose_name='자료유형')),
                ('book_author', models.CharField(blank=True, max_length=255, verbose_name='서명/저자')),
                ('book_personnel_author', models.CharField(blank=True, max_length=255, verbose_name='개인저자')),
                ('book_issue', models.CharField(blank=True, max_length=255, verbose_name='발행사항')),
                ('book_form', models.CharField(blank=True, max_length=255, verbose_name='형태사항')),
                ('IBSN', models.CharField(blank=True, max_length=255, verbose_name='IBSN')),
            ],
        ),
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(blank=True, max_length=100, verbose_name='등록번호')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='소장위치')),
                ('book_code', models.CharField(max_length=255, verbose_name='청구기호')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_location_list', to='books.BookLocation'),
        ),
    ]
