# Generated by Django 2.0.5 on 2018-05-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180523_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_location_list', to='books.BookLocation'),
        ),
    ]
