# Generated by Django 2.0.5 on 2018-06-01 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180523_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_location',
        ),
        migrations.AddField(
            model_name='booklocation',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_location_list', to='books.Book'),
        ),
    ]
