# Generated by Django 2.0.5 on 2018-07-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180702_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.TextField(blank=True, verbose_name='ISBN'),
        ),
    ]
