# Generated by Django 2.0.5 on 2018-07-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20180702_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.TextField(blank=True, verbose_name='자료유형'),
        ),
    ]
