# Generated by Django 2.0.5 on 2018-07-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20180702_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=255, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='서명/저자'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_form',
            field=models.CharField(blank=True, max_length=255, verbose_name='형태사항'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='자료유형'),
        ),
    ]
