# Generated by Django 2.0.6 on 2018-07-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20180702_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.TextField(blank=True, verbose_name='ISBN'),
        ),
    ]
