# Generated by Django 2.0.6 on 2018-07-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180706_1640'),
        ('books', '0014_auto_20180703_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.UserKeyword'),
        ),
    ]
