# Generated by Django 2.0.6 on 2018-07-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='keyword',
        ),
    ]
