# Generated by Django 2.0.5 on 2018-08-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.TextField(blank=True, verbose_name='서명/저자'),
        ),
    ]
