language: python
python:
- 3.6
services:
- postgresql
addons:
  postgresql: '9.4'
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_cc51d60ef425_key -iv $encrypted_cc51d60ef425_iv
  -in secrets.tar.enc -out secrets.tar -d;
  tar xvf secrets.tar;
  echo 'IS NOT PR';
  export DJANGO_SETTINGS_MODULE=config.settings.production;
  fi
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export DJANGO_SETTINGS_MODULE=config.settings.travis;
  echo 'IS PR';
  fi
install:
- pip install -r .requirements/production.txt
branches:
  only:
  - master
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- echo $DJANGO_SETTINGS_MODULE
- cd app
- "./manage.py test"
- cd ..
- git add -A
before_deploy:
- zip -r archive.zip .
deploy:
  provider: elasticbeanstalk
  zip_file: archive.zip
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: ap-northeast-2
  app: Toy-Project
  env: Toy-Project-dev
  bucket_name: toy-study-room
  skip_cleanup: true
  on:
    branch: master
