# Generated by Django 2.0.5 on 2018-05-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, verbose_name='검색키워드'),
        ),
    ]
