# Generated by Django 2.0.5 on 2018-05-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180523_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_keyword_list', to='members.UserKeyword'),
        ),
    ]
