# Generated by Django 2.0.5 on 2018-05-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180523_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_key',
        ),
    ]
