# Generated by Django 2.0.5 on 2018-06-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_user_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeyword',
            name='wrong_keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='찾지 못한 키워드'),
        ),
    ]
