# Generated by Django 2.0.5 on 2018-06-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_userkeyword_wrong_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='검색키워드'),
        ),
    ]
