# Generated by Django 2.0.5 on 2018-06-01 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180601_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keyword',
        ),
        migrations.AddField(
            model_name='userkeyword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_keyword_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
