# Generated by Django 2.0.5 on 2018-06-05 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180601_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeyword',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성시간'),
        ),
    ]
