# Generated by Django 2.0.6 on 2018-07-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_userkeyword_creation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lsat_visit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
