# Generated by Django 2.0.6 on 2018-07-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_user_lsat_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lsat_visit',
            new_name='last_visit',
        ),
    ]
