# Generated by Django 2.0.6 on 2018-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180706_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='creation_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='생성시간'),
        ),
    ]
