# Generated by Django 2.0.6 on 2018-07-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20180706_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_visit']},
        ),
        migrations.AlterModelOptions(
            name='userkeyword',
            options={'ordering': ['-creation_datetime']},
        ),
    ]
