# Generated by Django 2.0.5 on 2018-08-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20180706_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_visit']},
        ),
    ]
